// insert into genres (name) values ('Action'), ('Comedy'), ('Adventure'), ('Fantasy'), ('Sci-Fi'), ('Horror'), ('Thriller'), ('Drama'), ('History'), ('Mystery'), ('Animation'), ('Family'), ('Documentary');
//
// insert into crew (name, actor)  values ('Robby Benson', true), ('Jesse Corti', true), ('Rex Everhart', true), ('Angela Lansbury', true), ('Anthony LaPaglia', true), ('Samara Lee', true), ('Miranda Otto', true), ('Brad Greenquist', true), ('Steve Carell', true);
// insert into crew (name, actor) values ('Kristen Wiig', true), ('Trey Parker', true), ('Miranda Cosgrove', true), ('Tom Holland', true), ('Michael Keaton', true), ('Robert Downey Jr.', true), ('Marisa Tomei', true), ('Sandra Bullock', true), ('Jon Hamm', true);
// insert into crew (name, actor) values ('Michael Keaton', true), ('Allison Janney', true), ('Matthew McConaughey', true), ('Idris Elba', true), ('Tom Taylor', true), ('Dennis Haysbert', true), ('Anthony Bourdain', true), ('Fionn Whitehead', true), ('Damien Bonnard', true);
// insert into crew (name, actor) values ('Aneurin Barnard', true), ('Lee Armstrong', true), ('Ellen Burstyn', true), ('Mackenzie Foy', true), ('John Lithgow', true);
//
// //matching movies
//
// insert into movies (mongo_id, title, genres, awards, actors, production, ratings) values ('59b32929dba1c274429aa792', 'Beauty and the Beast', '[11, 12, 4]', 'Won 2 Oscars. Another 24 wins & 22 nominations.', '[1, 2, 3, 4]', 'Buena Vista', '[ { "Value" : "8.0/10", "Source" : "Internet Movie Database" }, { "Value" : "93%", "Source" : "Rotten Tomatoes" }, { "Value" : "95/100", "Source" : "Metacritic" } ]');
// insert into movies (mongo_id, title, genres, awards, actors, production, ratings) values ('59b32929dba1c274429aa793', 'Annabelle Movie', '[6, 10, 7]', '1 nomination', '[5, 6, 7, 8]', 'New Line Cinema', '[ { "Value" : "7.0/10", "Source" : "Internet Movie Database" }, { "Value" : "68%", "Source" : "Rotten Tomatoes" }, { "Value" : "62/100", "Source" : "Metacritic" } ]');
// insert into movies (mongo_id, title, genres, awards, actors, production, ratings) values ('59b32929dba1c274429aa794', 'Despicable Me', '[11, 1, 3]', '2 nominations', '[9, 10, 11, 12]', 'Universal Pictures', '[ { "Value" : "6.3/10", "Source" : "Internet Movie Database" }, { "Value" : "61%", "Source" : "Rotten Tomatoes" }, { "Value" : "49/100", "Source" : "Metacritic" } ]' );
// insert into movies (mongo_id, title, genres, actors, production, ratings) values ('59b32929dba1c274429aa796', 'Spiderman Homecoming', '[1, 3, 5]', '[13, 14, 15, 16]', 'Sony Pictures', '[ { "Value" : "7.9/10", "Source" : "Internet Movie Database" }, { "Value" : "92%", "Source" : "Rotten Tomatoes" }, { "Value" : "73/100", "Source" : "Metacritic" } ]');
// insert into movies (mongo_id, title, genres, awards, actors, production, ratings) values ('59b32929dba1c274429aa795', 'Minons Movie', '[11, 1, 3]', 'Nominated for 1 BAFTA Film Award. Another 3 wins & 20 nominations.', '[17, 18, 19, 20]', 'Universal Pictures', '[ { "Value" : "6.4/10", "Source" : "Internet Movie Database" }, { "Value" : "56%", "Source" : "Rotten Tomatoes" }, { "Value" : "56/100", "Source" : "Metacritic" } ]');
// insert into movies (mongo_id, title, genres, actors, production, ratings) values ('59b32929dba1c274429aa797', 'The Dark Tower', '[1, 3, 4]', '[21, 22, 23, 24]', 'Sony Pictures', '[ { "Value" : "6.0/10", "Source" : "Internet Movie Database" }, { "Value" : "16%", "Source" : "Rotten Tomatoes" }, { "Value" : "34/100", "Source" : "Metacritic" } ]');
// insert into movies (mongo_id, title, genres, actors, ratings) values ('59b32929dba1c274429aa798', 'The Layover', '13', '[25]', '[ { "Value" : "8.2/10", "Source" : "Internet Movie Database" } ]');
// insert into movies (mongo_id, title, genres, awards, actors, production, ratings) values ('59b32929dba1c274429aa799', 'Dunkirk', '[1, 8, 9]', '1 win & 2 nominations', '[26, 27, 28, 29]', 'Warner Bros. Pictures', '[ { "Value" : "8.4/10", "Source" : "Internet Movie Database" }, { "Value" : "93%", "Source" : "Rotten Tomatoes" }, { "Value" : "94/100", "Source" : "Metacritic" } ]');
// insert into movies (mongo_id, title, genres, awards, actors, production, ratings) values ('59b32929dba1c274429aa79a', 'Interstellar', '[3, 8, 5]', 'Won 1 Oscar. Another 43 wins & 143 nominations.', '[30, 31, 32, 21]', 'Paramount Pictures', '[ { "Value" : "8.6/10", "Source" : "Internet Movie Database" }, { "Value" : "71%", "Source" : "Rotten Tomatoes" }, { "Value" : "74/100", "Source" : "Metacritic" } ]');

//matt McConaughey is in two movies
//
// { "_id" : ObjectId("59b32929dba1c274429aa792"), "id" : 321612, "runtime" : "84 min", "poster" : "https://image.tmdb.org/t/p/w500/tWqifoYuwLETmmasnGHO7xBjEtt.jpg", "production" : "Buena Vista", "website" : "http://www.disney.com/beautyandthebeast", "theater" : [ ], "language" : [ "English, French" ], "ratings" : [ { "Value" : "8.0/10", "Source" : "Internet Movie Database" }, { "Value" : "93%", "Source" : "Rotten Tomatoes" }, { "Value" : "95/100", "Source" : "Metacritic" } ], "awards" : [ "Won 2 Oscars. Another 24 wins & 22 nominations." ], "actors" : [ "Robby Benson, Jesse Corti, Rex Everhart, Angela Lansbury" ], "writers" : [ ], "directors" : [ ], "genre" : [ "Animation, Family, Fantasy" ], "__v" : 0 }
// { "_id" : ObjectId("59b32929dba1c274429aa793"), "id" : 396422, "runtime" : "109 min", "poster" : "https://image.tmdb.org/t/p/w500/tb86j8jVCVsdZnzf8I6cIi65IeM.jpg", "production" : "New Line Cinema", "website" : "http://www.annabellemovie.com", "theater" : [ ], "language" : [ "English, Spanish" ], "ratings" : [ { "Value" : "7.0/10", "Source" : "Internet Movie Database" }, { "Value" : "68%", "Source" : "Rotten Tomatoes" }, { "Value" : "62/100", "Source" : "Metacritic" } ], "awards" : [ "1 nomination." ], "actors" : [ "Anthony LaPaglia, Samara Lee, Miranda Otto, Brad Greenquist" ], "writers" : [ ], "directors" : [ ], "genre" : [ "Horror, Mystery, Thriller" ], "__v" : 0 }
// { "_id" : ObjectId("59b32929dba1c274429aa794"), "id" : 324852, "runtime" : "90 min", "poster" : "https://image.tmdb.org/t/p/w500/5qcUGqWoWhEsoQwNUrtf3y3fcWn.jpg", "production" : "Universal Pictures", "website" : "http://www.despicable.me/", "theater" : [ ], "language" : [ "English" ], "ratings" : [ { "Value" : "6.3/10", "Source" : "Internet Movie Database" }, { "Value" : "61%", "Source" : "Rotten Tomatoes" }, { "Value" : "49/100", "Source" : "Metacritic" } ], "awards" : [ "2 nominations." ], "actors" : [ "Steve Carell, Kristen Wiig, Trey Parker, Miranda Cosgrove" ], "writers" : [ ], "directors" : [ ], "genre" : [ "Animation, Action, Adventure" ], "__v" : 0 }
// { "_id" : ObjectId("59b32929dba1c274429aa796"), "id" : 315635, "runtime" : "133 min", "poster" : "https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg", "production" : "Sony Pictures", "website" : "http://www.sonypictures.com/movies/spidermanhomecoming/", "theater" : [ ], "language" : [ "English" ], "ratings" : [ { "Value" : "7.9/10", "Source" : "Internet Movie Database" }, { "Value" : "92%", "Source" : "Rotten Tomatoes" }, { "Value" : "73/100", "Source" : "Metacritic" } ], "awards" : [ "N/A" ], "actors" : [ "Tom Holland, Michael Keaton, Robert Downey Jr., Marisa Tomei" ], "writers" : [ ], "directors" : [ ], "genre" : [ "Action, Adventure, Sci-Fi" ], "__v" : 0 }
// { "_id" : ObjectId("59b32929dba1c274429aa795"), "id" : 211672, "runtime" : "91 min", "poster" : "https://image.tmdb.org/t/p/w500/q0R4crx2SehcEEQEkYObktdeFy.jpg", "production" : "Universal Pictures", "website" : "http://www.minionsmovie.com/", "theater" : [ ], "language" : [ "English, Spanish" ], "ratings" : [ { "Value" : "6.4/10", "Source" : "Internet Movie Database" }, { "Value" : "56%", "Source" : "Rotten Tomatoes" }, { "Value" : "56/100", "Source" : "Metacritic" } ], "awards" : [ "Nominated for 1 BAFTA Film Award. Another 3 wins & 20 nominations." ], "actors" : [ "Sandra Bullock, Jon Hamm, Michael Keaton, Allison Janney" ], "writers" : [ ], "directors" : [ ], "genre" : [ "Animation, Action, Adventure" ], "__v" : 0 }
// { "_id" : ObjectId("59b32929dba1c274429aa797"), "id" : 353491, "runtime" : "95 min", "poster" : "https://image.tmdb.org/t/p/w500/i9GUSgddIqrroubiLsvvMRYyRy0.jpg", "production" : "Sony Pictures", "website" : "N/A", "theater" : [ ], "language" : [ "English" ], "ratings" : [ { "Value" : "6.0/10", "Source" : "Internet Movie Database" }, { "Value" : "16%", "Source" : "Rotten Tomatoes" }, { "Value" : "34/100", "Source" : "Metacritic" } ], "awards" : [ "N/A" ], "actors" : [ "Matthew McConaughey, Idris Elba, Tom Taylor, Dennis Haysbert" ], "writers" : [ ], "directors" : [ ], "genre" : [ "Action, Adventure, Fantasy" ], "__v" : 0 }
// { "_id" : ObjectId("59b32929dba1c274429aa798"), "id" : 339404, "runtime" : "43 min", "poster" : "https://image.tmdb.org/t/p/w500/kb9osnqanXRpkpm1bnSqAhKoq5T.jpg", "theater" : [ ], "language" : [ "English" ], "ratings" : [ { "Value" : "8.2/10", "Source" : "Internet Movie Database" } ], "awards" : [ "N/A" ], "actors" : [ "Anthony Bourdain" ], "writers" : [ ], "directors" : [ ], "genre" : [ "Documentary" ], "__v" : 0 }
// { "_id" : ObjectId("59b32929dba1c274429aa799"), "id" : 374720, "runtime" : "106 min", "poster" : "https://image.tmdb.org/t/p/w500/bOXBV303Fgkzn2K4FeKDc0O31q4.jpg", "production" : "Warner Bros. Pictures", "website" : "http://www.dunkirkmovie.com", "theater" : [ ], "language" : [ "English, French, German" ], "ratings" : [ { "Value" : "8.4/10", "Source" : "Internet Movie Database" }, { "Value" : "93%", "Source" : "Rotten Tomatoes" }, { "Value" : "94/100", "Source" : "Metacritic" } ], "awards" : [ "1 win & 2 nominations." ], "actors" : [ "Fionn Whitehead, Damien Bonnard, Aneurin Barnard, Lee Armstrong" ], "writers" : [ ], "directors" : [ ], "genre" : [ "Action, Drama, History" ], "__v" : 0 }
// { "_id" : ObjectId("59b32929dba1c274429aa79a"), "id" : 157336, "runtime" : "169 min", "poster" : "https://image.tmdb.org/t/p/w500/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg", "production" : "Paramount Pictures", "website" : "http://www.InterstellarMovie.com/", "theater" : [ ], "language" : [ "English" ], "ratings" : [ { "Value" : "8.6/10", "Source" : "Internet Movie Database" }, { "Value" : "71%", "Source" : "Rotten Tomatoes" }, { "Value" : "74/100", "Source" : "Metacritic" } ], "awards" : [ "Won 1 Oscar. Another 43 wins & 143 nominations." ], "actors" : [ "Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow" ], "writers" : [ ], "directors" : [ ], "genre" : [ "Adventure, Drama, Sci-Fi" ], "__v" : 0 }
