var data = [{
"Title":"Black Swan",
"Year":"2010",
"Rated":"R",
"Released":"17 Dec 2010",
"Runtime":"108 min",
"Genre":"Drama, Thriller",
"Director":"Darren Aronofsky",
"Writer":"Mark Heyman (screenplay), Andres Heinz (screenplay), John J. McLaughlin (screenplay), Andres Heinz (story)",
"Actors":"Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey",
"Plot":"Nina (Portman) is a ballerina in a New York City ballet company whose life, like all those in her profession, is completely consumed with dance. She lives with her obsessive former ballerina mother Erica (Hershey) who exerts a suffocating control over her. When artistic director Thomas Leroy (Cassel) decides to replace prima ballerina Beth MacIntyre (Ryder) for the opening production of their new season, Swan Lake, Nina is his first choice. But Nina has competition: a new dancer, Lily (Kunis), who impresses Leroy as well. Swan Lake requires a dancer who can play both the White Swan with innocence and grace, and the Black Swan, who represents guile and sensuality. Nina fits the White Swan role perfectly but Lily is the personification of the Black Swan. As the two young dancers expand their rivalry into a twisted friendship, Nina begins to get more in touch with her dark side - a recklessness that threatens to destroy her.",
"Language":"English, French, Italian",
"Country":"USA",
"Awards":"Won 1 Oscar. Another 91 wins & 257 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"79/100"}],
"Metascore":"79",
"imdbRating":"8.0",
"imdbVotes":"589,871",
"imdbID":"tt0947798",
"Type":"movie",
"DVD":"29 Mar 2011",
"BoxOffice":"$106,952,327",
"Production":"Fox Searchlight",
"Website":"http://www.BlackSwan2010.com/",
"Response":"True"},

{
"Title":"Black Swan",
"Year":"2010",
"Rated":"R",
"Released":"17 Dec 2010",
"Runtime":"108 min",
"Genre":"Drama, Thriller",
"Director":"Darren Aronofsky",
"Writer":"Mark Heyman (screenplay), Andres Heinz (screenplay), John J. McLaughlin (screenplay), Andres Heinz (story)",
"Actors":"Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey",
"Plot":"Nina (Portman) is a ballerina in a New York City ballet company whose life, like all those in her profession, is completely consumed with dance. She lives with her obsessive former ballerina mother Erica (Hershey) who exerts a suffocating control over her. When artistic director Thomas Leroy (Cassel) decides to replace prima ballerina Beth MacIntyre (Ryder) for the opening production of their new season, Swan Lake, Nina is his first choice. But Nina has competition: a new dancer, Lily (Kunis), who impresses Leroy as well. Swan Lake requires a dancer who can play both the White Swan with innocence and grace, and the Black Swan, who represents guile and sensuality. Nina fits the White Swan role perfectly but Lily is the personification of the Black Swan. As the two young dancers expand their rivalry into a twisted friendship, Nina begins to get more in touch with her dark side - a recklessness that threatens to destroy her.",
"Language":"English, French, Italian",
"Country":"USA",
"Awards":"Won 1 Oscar. Another 91 wins & 257 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"79/100"}],
"Metascore":"79",
"imdbRating":"8.0",
"imdbVotes":"589,871",
"imdbID":"tt0947798",
"Type":"movie",
"DVD":"29 Mar 2011",
"BoxOffice":"$106,952,327",
"Production":"Fox Searchlight",
"Website":"http://www.BlackSwan2010.com/",
"Response":"True"},

{
"Title":"Black Swan",
"Year":"2010",
"Rated":"R",
"Released":"17 Dec 2010",
"Runtime":"108 min",
"Genre":"Drama, Thriller",
"Director":"Darren Aronofsky",
"Writer":"Mark Heyman (screenplay), Andres Heinz (screenplay), John J. McLaughlin (screenplay), Andres Heinz (story)",
"Actors":"Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey",
"Plot":"Nina (Portman) is a ballerina in a New York City ballet company whose life, like all those in her profession, is completely consumed with dance. She lives with her obsessive former ballerina mother Erica (Hershey) who exerts a suffocating control over her. When artistic director Thomas Leroy (Cassel) decides to replace prima ballerina Beth MacIntyre (Ryder) for the opening production of their new season, Swan Lake, Nina is his first choice. But Nina has competition: a new dancer, Lily (Kunis), who impresses Leroy as well. Swan Lake requires a dancer who can play both the White Swan with innocence and grace, and the Black Swan, who represents guile and sensuality. Nina fits the White Swan role perfectly but Lily is the personification of the Black Swan. As the two young dancers expand their rivalry into a twisted friendship, Nina begins to get more in touch with her dark side - a recklessness that threatens to destroy her.",
"Language":"English, French, Italian",
"Country":"USA",
"Awards":"Won 1 Oscar. Another 91 wins & 257 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"79/100"}],
"Metascore":"79",
"imdbRating":"8.0",
"imdbVotes":"589,871",
"imdbID":"tt0947798",
"Type":"movie",
"DVD":"29 Mar 2011",
"BoxOffice":"$106,952,327",
"Production":"Fox Searchlight",
"Website":"http://www.BlackSwan2010.com/",
"Response":"True"}, 

{
"Title":"Black Swan",
"Year":"2010",
"Rated":"R",
"Released":"17 Dec 2010",
"Runtime":"108 min",
"Genre":"Drama, Thriller",
"Director":"Darren Aronofsky",
"Writer":"Mark Heyman (screenplay), Andres Heinz (screenplay), John J. McLaughlin (screenplay), Andres Heinz (story)",
"Actors":"Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey",
"Plot":"Nina (Portman) is a ballerina in a New York City ballet company whose life, like all those in her profession, is completely consumed with dance. She lives with her obsessive former ballerina mother Erica (Hershey) who exerts a suffocating control over her. When artistic director Thomas Leroy (Cassel) decides to replace prima ballerina Beth MacIntyre (Ryder) for the opening production of their new season, Swan Lake, Nina is his first choice. But Nina has competition: a new dancer, Lily (Kunis), who impresses Leroy as well. Swan Lake requires a dancer who can play both the White Swan with innocence and grace, and the Black Swan, who represents guile and sensuality. Nina fits the White Swan role perfectly but Lily is the personification of the Black Swan. As the two young dancers expand their rivalry into a twisted friendship, Nina begins to get more in touch with her dark side - a recklessness that threatens to destroy her.",
"Language":"English, French, Italian",
"Country":"USA",
"Awards":"Won 1 Oscar. Another 91 wins & 257 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"79/100"}],
"Metascore":"79",
"imdbRating":"8.0",
"imdbVotes":"589,871",
"imdbID":"tt0947798",
"Type":"movie",
"DVD":"29 Mar 2011",
"BoxOffice":"$106,952,327",
"Production":"Fox Searchlight",
"Website":"http://www.BlackSwan2010.com/",
"Response":"True"},

{
"Title":"Black Swan",
"Year":"2010",
"Rated":"R",
"Released":"17 Dec 2010",
"Runtime":"108 min",
"Genre":"Drama, Thriller",
"Director":"Darren Aronofsky",
"Writer":"Mark Heyman (screenplay), Andres Heinz (screenplay), John J. McLaughlin (screenplay), Andres Heinz (story)",
"Actors":"Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey",
"Plot":"Nina (Portman) is a ballerina in a New York City ballet company whose life, like all those in her profession, is completely consumed with dance. She lives with her obsessive former ballerina mother Erica (Hershey) who exerts a suffocating control over her. When artistic director Thomas Leroy (Cassel) decides to replace prima ballerina Beth MacIntyre (Ryder) for the opening production of their new season, Swan Lake, Nina is his first choice. But Nina has competition: a new dancer, Lily (Kunis), who impresses Leroy as well. Swan Lake requires a dancer who can play both the White Swan with innocence and grace, and the Black Swan, who represents guile and sensuality. Nina fits the White Swan role perfectly but Lily is the personification of the Black Swan. As the two young dancers expand their rivalry into a twisted friendship, Nina begins to get more in touch with her dark side - a recklessness that threatens to destroy her.",
"Language":"English, French, Italian",
"Country":"USA",
"Awards":"Won 1 Oscar. Another 91 wins & 257 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"79/100"}],
"Metascore":"79",
"imdbRating":"8.0",
"imdbVotes":"589,871",
"imdbID":"tt0947798",
"Type":"movie",
"DVD":"29 Mar 2011",
"BoxOffice":"$106,952,327",
"Production":"Fox Searchlight",
"Website":"http://www.BlackSwan2010.com/",
"Response":"True"},

{
"Title":"Black Swan",
"Year":"2010",
"Rated":"R",
"Released":"17 Dec 2010",
"Runtime":"108 min",
"Genre":"Drama, Thriller",
"Director":"Darren Aronofsky",
"Writer":"Mark Heyman (screenplay), Andres Heinz (screenplay), John J. McLaughlin (screenplay), Andres Heinz (story)",
"Actors":"Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey",
"Plot":"Nina (Portman) is a ballerina in a New York City ballet company whose life, like all those in her profession, is completely consumed with dance. She lives with her obsessive former ballerina mother Erica (Hershey) who exerts a suffocating control over her. When artistic director Thomas Leroy (Cassel) decides to replace prima ballerina Beth MacIntyre (Ryder) for the opening production of their new season, Swan Lake, Nina is his first choice. But Nina has competition: a new dancer, Lily (Kunis), who impresses Leroy as well. Swan Lake requires a dancer who can play both the White Swan with innocence and grace, and the Black Swan, who represents guile and sensuality. Nina fits the White Swan role perfectly but Lily is the personification of the Black Swan. As the two young dancers expand their rivalry into a twisted friendship, Nina begins to get more in touch with her dark side - a recklessness that threatens to destroy her.",
"Language":"English, French, Italian",
"Country":"USA",
"Awards":"Won 1 Oscar. Another 91 wins & 257 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"79/100"}],
"Metascore":"79",
"imdbRating":"8.0",
"imdbVotes":"589,871",
"imdbID":"tt0947798",
"Type":"movie",
"DVD":"29 Mar 2011",
"BoxOffice":"$106,952,327",
"Production":"Fox Searchlight",
"Website":"http://www.BlackSwan2010.com/",
"Response":"True"}];


export default data;