var data = [{
"Title":"Black Swan",
"Year":"2010",
"Rated":"R",
"Released":"17 Dec 2010",
"Runtime":"108 min",
"Genre":"Drama, Thriller",
"Director":"Darren Aronofsky",
"Writer":"Mark Heyman (screenplay), Andres Heinz (screenplay), John J. McLaughlin (screenplay), Andres Heinz (story)",
"Actors":"Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey",
"Plot":"Nina (Portman) is a ballerina in a New York City ballet company whose life, like all those in her profession, is completely consumed with dance. She lives with her obsessive former ballerina mother Erica (Hershey) who exerts a suffocating control over her. When artistic director Thomas Leroy (Cassel) decides to replace prima ballerina Beth MacIntyre (Ryder) for the opening production of their new season, Swan Lake, Nina is his first choice. But Nina has competition: a new dancer, Lily (Kunis), who impresses Leroy as well. Swan Lake requires a dancer who can play both the White Swan with innocence and grace, and the Black Swan, who represents guile and sensuality. Nina fits the White Swan role perfectly but Lily is the personification of the Black Swan. As the two young dancers expand their rivalry into a twisted friendship, Nina begins to get more in touch with her dark side - a recklessness that threatens to destroy her.",
"Language":"English, French, Italian",
"Country":"USA",
"Awards":"Won 1 Oscar. Another 91 wins & 257 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"79/100"}],
"Metascore":"79",
"imdbRating":"8.0",
"imdbVotes":"589,871",
"imdbID":"tt0947798",
"Type":"movie",
"DVD":"29 Mar 2011",
"BoxOffice":"$106,952,327",
"Production":"Fox Searchlight",
"Website":"http://www.BlackSwan2010.com/",
"Response":"True"},

{"Title":"Lego Indiana Jones and the Raiders of the Lost Brick","Year":"2008","Rated":"N/A","Released":"10 May 2008","Runtime":"5 min","Genre":"Animation, Short, Adventure","Director":"Peder Pedersen","Writer":"Ole Holm Christensen (story), Thomas Sebastian Fenger (story), Keith Malone (story), Peder Pedersen (story)","Actors":"N/A",
"Plot":"Four shorts based on all four Indiana Jones movies with a little Lego twist and inside jokes.",
"Language":"English",
"Country":"Denmark",
"Awards":"N/A",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjA0MDE3ODY2OV5BMl5BanBnXkFtZTcwNjM3ODc4Mg@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"}],
"Metascore":"N/A",
"imdbRating":"7.4",
"imdbVotes":"270",
"imdbID":"tt1504682",
"Type":"movie",
"DVD":"N/A",
"BoxOffice":"N/A",
"Production":"N/A",
"Website":"N/A",
"Response":"True"},

{"Title":"Raiders of the Lost Ark",
"Year":"1981",
"Rated":"PG",
"Released":"12 Jun 1981",
"Runtime":"115 min",
"Genre":"Action, Adventure",
"Director":"Steven Spielberg",
"Writer":"Lawrence Kasdan (screenplay), George Lucas (story by), Philip Kaufman (story by)",
"Actors":"Harrison Ford, Karen Allen, Paul Freeman, Ronald Lacey",
"Plot":"The year is 1936. An archeology professor named Indiana Jones is venturing in the jungles of South America searching for a golden statue. Unfortunately, he sets off a deadly trap but miraculously escapes. Then, Jones hears from a museum curator named Marcus Brody about a biblical artifact called The Ark of the Covenant, which can hold the key to humanly existence. Jones has to venture to vast places such as Nepal and Egypt to find this artifact. However, he will have to fight his enemy Rene Belloq and a band of Nazis in order to reach it.",
"Language":"English, German, Hebrew, Spanish, Arabic, Nepali",
"Country":"USA",
"Awards":"Won 4 Oscars. Another 30 wins & 23 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjA0ODEzMTc1Nl5BMl5BanBnXkFtZTcwODM2MjAxNA@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"85/100"}],
"Metascore":"85",
"imdbRating":"8.5",
"imdbVotes":"718,669",
"imdbID":"tt0082971",
"Type":"movie",
"DVD":"21 Oct 2003",
"BoxOffice":"N/A",
"Production":"Paramount Pictures",
"Website":"http://www.indianajones.com/raiders/",
"Response":"True"},

{"Title":"The Raid: Redemption",
"Year":"2011",
"Rated":"R",
"Released":"13 Apr 2012",
"Runtime":"101 min",
"Genre":"Action, Crime, Thriller",
"Director":"Gareth Evans","Writer":"Gareth Evans",
"Actors":"Iko Uwais, Joe Taslim, Donny Alamsyah, Yayan Ruhian",
"Plot":"In Jakarta, Indonesia, Lieutenant Wahyu organizes the invasion of an apartment building that is the safe house of the powerful and cruel drug lord Tama and his gang. The SWAT team breaks in the building but one lookout sees and warns the gangsters and the police force is trapped on the seventh floor. They learn that Lt. Wahyu has not informed his superiors about the operation. Now the police officers have to fight with limited ammunition against the armed and dangerous gangsters.",
"Language":"Indonesian",
"Country":"Indonesia, France, USA",
"Awards":"6 wins & 11 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZGIxODNjM2YtZjA5Mi00MjA5LTk2YjItODE0OWI5NThjNTBmXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"7.6/10"},{"Source":"Rotten Tomatoes","Value":"85%"},{"Source":"Metacritic","Value":"73/100"}],
"Metascore":"73",
"imdbRating":"7.6",
"imdbVotes":"159,716",
"imdbID":"tt1899353",
"Type":"movie",
"DVD":"14 Aug 2012",
"BoxOffice":"$1,200,000",
"Production":"Sony Pictures Classics",
"Website":"http://www.theraidmovie.com",
"Response":"True"},

{"Title":"Happy Feet",
"Year":"2006",
"Rated":"PG",
"Released":"17 Nov 2006",
"Runtime":"108 min",
"Genre":"Animation, Comedy, Family",
"Director":"George Miller, Warren Coleman, Judy Morris",
"Writer":"George Miller, John Collee, Judy Morris, Warren Coleman",
"Actors":"Carlos Alazraqui, Lombardo Boyar, Jeffrey Garcia, Johnny A. Sanchez",
"Plot":"This is the story of a little penguin named Mumble who has a terrible singing voice and later discovers he has no Heartsong. However, Mumble has an astute talent for something that none of the penguins had ever seen before: tap dancing. Though Mumble's mom, Norma Jean, thinks this little habit is cute, his dad, Memphis, says it \"just ain't penguin.\" Besides, they both know that, without a Heartsong, Mumble may never find true love. As fate would have it, his one friend, Gloria, happens to be the best singer around. Mumble and Gloria have a connection from the moment they hatch, but she struggles with his strange \"hippity- hoppity\" ways. Mumble is just too different--especially for Noah the Elder, the stern leader of Emperor Land, who ultimately casts him out of the community. Away from home for the first time, Mumble meets a posse of decidedly un-Emperor-like penguins--the Adelie Amigos. Led by Ramon, the Adelies instantly embrace Mumble's cool dance moves and invite him to party with them. In Adelie Land, Mumble seeks the counsel of Lovelace the Guru, a crazy-feathered Rockhopper penguin who will answer any of life's questions for the price of a pebble. Together with Lovelace and the Amigos, Mumble sets out across vast landscapes and, after some epic encounters, proves that by being true to yourself, you can make all the difference in the world.",
"Language":"English",
"Country":"USA, Australia",
"Awards":"Won 1 Oscar. Another 18 wins & 23 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTQyNTkxMjUwMV5BMl5BanBnXkFtZTcwMDQ2NTU0MQ@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"6.5/10"},
  {"Source":"Rotten Tomatoes","Value":"75%"},
  {"Source":"Metacritic","Value":"77/100"}],
"Metascore":"77",
"imdbRating":"6.5",
"imdbVotes":"143,047",
"imdbID":"tt0366548",
"Type":"movie",
"DVD":"27 Mar 2007",
"BoxOffice":"$197,800,000",
"Production":"Warner Bros. Pictures",
"Website":"http://www.happyfeetmovie.com/",
"Response":"True"},

{"Title":"Cloud Atlas",
"Year":"2012",
"Rated":"R",
"Released":"26 Oct 2012",
"Runtime":"172 min",
"Genre":"Action, Drama, Mystery",
"Director":"Tom Tykwer, Lana Wachowski, Lilly Wachowski",
"Writer":"David Mitchell (novel), Lana Wachowski (written for the screen by), Tom Tykwer (written for the screen by), Lilly Wachowski (written for the screen by)",
"Actors":"Tom Hanks, Halle Berry, Jim Broadbent, Hugo Weaving",
"Plot":"Everything is connected: an 1849 diary of an ocean voyage across the Pacific; letters from a composer to his lover; a thriller about a conspiracy at a nuclear power plant; a farce about a publisher in a nursing home; a rebellious clone in futuristic Korea; and the tale of a tribe living on post-apocalyptic Hawaii far in the future.",
"Language":"English, Spanish, Ukrainian",
"Country":"Germany, USA, Hong Kong, Singapore",
"Awards":"Nominated for 1 Golden Globe. Another 16 wins & 75 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTczMTgxMjc4NF5BMl5BanBnXkFtZTcwNjM5MTA2OA@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"7.5/10"},
  {"Source":"Rotten Tomatoes","Value":"66%"},
  {"Source":"Metacritic","Value":"55/100"}],
"Metascore":"55",
"imdbRating":"7.5",
"imdbVotes":"302,442",
"imdbID":"tt1371111",
"Type":"movie",
"DVD":"14 May 2013",
"BoxOffice":"$22,100,000",
"Production":"Warner Bros. Pictures",
"Website":"http://www.cloudatlasmovie.com",
"Response":"True"},

{"Title":"Ted",
"Year":"2012",
"Rated":"R",
"Released":"29 Jun 2012",
"Runtime":"106 min",
"Genre":"Comedy, Fantasy",
"Director":"Seth MacFarlane",
"Writer":"Seth MacFarlane (screenplay), Alec Sulkin (screenplay), Wellesley Wild (screenplay), Seth MacFarlane (story by)",
"Actors":"Mark Wahlberg, Mila Kunis, Seth MacFarlane, Joel McHale",
"Plot":"John makes a Christmas miracle happen by bringing his one and only friend to life, his teddy bear. The two grow up together and John must then choose to stay with his girlfriend or keep his friendship with his crude and extremely inappropriate teddy bear, Ted.",
"Language":"English, Ukrainian",
"Country":"USA",
"Awards":"Nominated for 1 Oscar. Another 13 wins & 27 nominations.",
"Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ1OTU0ODcxMV5BMl5BanBnXkFtZTcwOTMxNTUwOA@@._V1_SX300.jpg",
"Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},
  {"Source":"Rotten Tomatoes","Value":"67%"},
  {"Source":"Metacritic","Value":"62/100"}],
"Metascore":"62",
"imdbRating":"7.0",
"imdbVotes":"500,290",
"imdbID":"tt1637725",
"Type":"movie",
"DVD":"11 Dec 2012",
"BoxOffice":"$218,100,000",
"Production":"Universal Pictures",
"Website":"http://www.tedisreal.com/",
"Response":"True"}];

export default data;