var datatwo = [{"Title":"Cloud Atlas",
  "Year":"2012",
  "Rated":"R",
  "Released":"26 Oct 2012",
  "Runtime":"172 min",
  "Genre":"Action, Drama, Mystery",
  "Director":"Tom Tykwer, Lana Wachowski, Lilly Wachowski",
  "Writer":"David Mitchell (novel), Lana Wachowski (written for the screen by), Tom Tykwer (written for the screen by), Lilly Wachowski (written for the screen by)",
  "Actors":"Tom Hanks, Halle Berry, Jim Broadbent, Hugo Weaving",
  "Plot":"Everything is connected: an 1849 diary of an ocean voyage across the Pacific; letters from a composer to his lover; a thriller about a conspiracy at a nuclear power plant; a farce about a publisher in a nursing home; a rebellious clone in futuristic Korea; and the tale of a tribe living on post-apocalyptic Hawaii far in the future.",
  "Language":"English, Spanish, Ukrainian",
  "Country":"Germany, USA, Hong Kong, Singapore",
  "Awards":"Nominated for 1 Golden Globe. Another 16 wins & 75 nominations.",
  "Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTczMTgxMjc4NF5BMl5BanBnXkFtZTcwNjM5MTA2OA@@._V1_SX300.jpg",
  "Ratings":[{"Source":"Internet Movie Database","Value":"7.5/10"},
    {"Source":"Rotten Tomatoes","Value":"66%"},
    {"Source":"Metacritic","Value":"55/100"}],
  "Metascore":"55",
  "imdbRating":"7.5",
  "imdbVotes":"302,442",
  "imdbID":"tt1371111",
  "Type":"movie",
  "DVD":"14 May 2013",
  "BoxOffice":"$22,100,000",
  "Production":"Warner Bros. Pictures",
  "Website":"http://www.cloudatlasmovie.com",
  "Response":"True"},

{"Title":"Ted",
  "Year":"2012",
  "Rated":"R",
  "Released":"29 Jun 2012",
  "Runtime":"106 min",
  "Genre":"Comedy, Fantasy",
  "Director":"Seth MacFarlane",
  "Writer":"Seth MacFarlane (screenplay), Alec Sulkin (screenplay), Wellesley Wild (screenplay), Seth MacFarlane (story by)",
  "Actors":"Mark Wahlberg, Mila Kunis, Seth MacFarlane, Joel McHale",
  "Plot":"John makes a Christmas miracle happen by bringing his one and only friend to life, his teddy bear. The two grow up together and John must then choose to stay with his girlfriend or keep his friendship with his crude and extremely inappropriate teddy bear, Ted.",
  "Language":"English, Ukrainian",
  "Country":"USA",
  "Awards":"Nominated for 1 Oscar. Another 13 wins & 27 nominations.",
  "Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ1OTU0ODcxMV5BMl5BanBnXkFtZTcwOTMxNTUwOA@@._V1_SX300.jpg",
  "Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},
    {"Source":"Rotten Tomatoes","Value":"67%"},
    {"Source":"Metacritic","Value":"62/100"}],
  "Metascore":"62",
  "imdbRating":"7.0",
  "imdbVotes":"500,290",
  "imdbID":"tt1637725",
  "Type":"movie",
  "DVD":"11 Dec 2012",
  "BoxOffice":"$218,100,000",
  "Production":"Universal Pictures",
  "Website":"http://www.tedisreal.com/",
  "Response":"True"}
];

module.exports = datatwo;
